"""
Django settings for FeedbackSystem project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from decouple import config
from unipath import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).parent
# CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent
CORE_DIR = BASE_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ji7-7p_eymc-m%e*48#ew+dpqrmg-+7eslvch#9yk3k%lm=ewa"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'FeedbackSystem.dashboard.apps.home',

    #own apps
    'FeedbackSystem.userside.Authentication',
    'crispy_forms',
    'bootstrap4',

    #forms
    'FeedbackSystem.forms.app',

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ROOT_URLCONF = 'core.urls'
ROOT_URLCONF = "FeedbackSystem.urls"
LOGIN_REDIRECT_URL = ""  # Route defined in home/urls.py
LOGOUT_REDIRECT_URL = ""  # Route defined in home/urls.py  we need this to remain empty so the the different logout urls are executed
TEMPLATE_DIR = os.path.join(CORE_DIR, "FeedbackSystem/dashboard/apps/templates")  # ROOT dir for templates
TEMPLATE_DIR_USERSIDE = os.path.join(CORE_DIR, "FeedbackSystem/userside/Authentication/apps/templates")
TEMPLATE_DIR_FORMS = os.path.join(CORE_DIR, "FeedbackSystem/forms/app/templates")
# ROOT_URLCONF = "FeedbackSystem.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATE_DIR, TEMPLATE_DIR_USERSIDE, TEMPLATE_DIR_FORMS],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },  
]

WSGI_APPLICATION = "FeedbackSystem.wsgi.application"

CRISPY_TEMPLATE_PACK = 'bootstrap4'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "db.sqlite3",

    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(CORE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
# STATICFILES_DIRS = (
#     os.path.join(CORE_DIR, 'FeedbackSystem/dashboard/apps/static', 'FeedbackSystem/userside/Authentication/static')),
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'FeedbackSystem/dashboard/apps/static'),
    os.path.join(BASE_DIR, 'FeedbackSystem/userside/Authentication/static'),
    os.path.join(BASE_DIR, 'FeedbackSystem/forms/app/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'home_user'


# LOGIN_URL = 'login'
LOGIN_URL = 'login_user'