# Generated by Django 4.2.4 on 2023-08-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('q1_choice', models.CharField(choices=[('5', 'Very Satisfied'), ('4', 'Satisfied'), ('3', 'Neutral'), ('2', 'Dissatisfied'), ('1', 'Very Dissatisfied')], max_length=10)),
                ('q2_choice', models.CharField(choices=[('5', 'Strongly Agree'), ('4', 'Agree'), ('3', 'Neutral'), ('2', 'Disagree'), ('1', 'Strongly Disagree')], max_length=10)),
                ('comments_campus', models.TextField()),
                ('preferred_building', models.CharField(choices=[('building_a', 'Building A'), ('building_b', 'Building B'), ('building_c', 'Building C')], max_length=50)),
                ('visit_frequency', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('course_unit', models.CharField(max_length=100)),
                ('rating_instructor', models.PositiveSmallIntegerField()),
                ('comments_course', models.TextField()),
                ('q1_choice', models.CharField(choices=[('5', 'Very Satisfied'), ('4', 'Satisfied'), ('3', 'Neutral'), ('2', 'Dissatisfied'), ('1', 'Very Dissatisfied')], max_length=10)),
                ('q2_choice', models.CharField(choices=[('5', 'Strongly Agree'), ('4', 'Agree'), ('3', 'Neutral'), ('2', 'Disagree'), ('1', 'Strongly Disagree')], max_length=10)),
                ('suggestion', models.CharField(blank=True, max_length=500, null=True)),
                ('additional_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('instructor_name', models.CharField(max_length=100)),
                ('rating_instructor', models.PositiveSmallIntegerField()),
                ('comments_instructor', models.TextField()),
                ('q1_choice', models.CharField(choices=[('5', 'Very Satisfied'), ('4', 'Satisfied'), ('3', 'Neutral'), ('2', 'Dissatisfied'), ('1', 'Very Dissatisfied')], max_length=10)),
                ('q2_choice', models.CharField(choices=[('5', 'Strongly Agree'), ('4', 'Agree'), ('3', 'Neutral'), ('2', 'Disagree'), ('1', 'Strongly Disagree')], max_length=10)),
                ('suggestion', models.CharField(blank=True, max_length=500, null=True)),
                ('additional_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
    ]
