# Generated by Django 4.2.4 on 2023-08-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_facilities', models.CharField(choices=[('5', 'Very Satisfied'), ('4', 'Satisfied'), ('3', 'Neutral'), ('2', 'Dissatisfied'), ('1', 'Very Dissatisfied')], max_length=10)),
                ('cleanliness_maintanance', models.CharField(choices=[('5', 'Very Clean'), ('4', 'Clean'), ('3', 'Neutral'), ('2', 'Dirty'), ('1', 'Very Dirty')], max_length=10)),
                ('campus_resources', models.CharField(choices=[('5', 'Very Accessible'), ('4', 'Accessible'), ('3', 'Neutral'), ('2', 'Unaccessible'), ('1', 'Very Unaccessible')], max_length=10)),
                ('campus_security', models.CharField(choices=[('5', 'Very Satisfied'), ('4', 'Satisfied'), ('3', 'Neutral'), ('2', 'Dissatisfied'), ('1', 'Very Dissatisfied')], max_length=10)),
                ('comments_campus', models.TextField()),
                ('preferred_building', models.CharField(choices=[('building_a', 'COSCIS main building'), ('building_b', 'College Library'), ('building_c', 'Auditorium')], max_length=50)),
                ('visit_frequency', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('select_course', models.CharField(choices=[('software_engineering', 'Bachelor of Science in Software Engineering'), ('computer_science', 'Bachelor of Science in Computer Science'), ('infosystems_technology', 'Bachelor of Science in Information Systems and Technology')], max_length=50)),
                ('select_year', models.CharField(choices=[('year_1', 'YEAR 1'), ('year_2', 'YEAR 2'), ('year_3', 'YEAR 3'), ('year_4', 'YEAR 4')], max_length=50)),
                ('course_unit', models.CharField(choices=[('courseunit_1', 'Mobile Programming'), ('courseunit_2', 'Requirements Engineering'), ('courseunit_3', 'Artificial Intelligence'), ('courseunit_4', 'Data Communication'), ('courseunit_5', 'Object Oriented Programming'), ('courseunit_6', 'Computer Networks'), ('courseunit_7', 'Operating Systems'), ('courseunit_8', 'Database Management'), ('courseunit_9', 'Emerging Web Technologies'), ('courseunit_10', 'Data Structures and Algorithms')], max_length=50)),
                ('rating_instructor', models.PositiveSmallIntegerField()),
                ('comments_course', models.TextField()),
                ('course_satisfaction', models.CharField(choices=[('5', 'Very Satisfied'), ('4', 'Satisfied'), ('3', 'Neutral'), ('2', 'Dissatisfied'), ('1', 'Very Dissatisfied')], max_length=10)),
                ('course_remarks', models.CharField(choices=[('5', 'Strongly Agree'), ('4', 'Agree'), ('3', 'Neutral'), ('2', 'Disagree'), ('1', 'Strongly Disagree')], max_length=10)),
                ('suggestion', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(choices=[('mumbere_alice', 'Dr Mumbere Alice'), ('agaba_martha', 'Dr Agaba Martha'), ('rogers_ntanda', 'Professor Rogers Ntanda'), ('ariho_geoffrey', 'Dr Ariho Geoffrey'), ('birimumaaso_conrad', 'Dr Birimumaaso Conrad')], max_length=50)),
                ('rating_instructor', models.PositiveSmallIntegerField()),
                ('comments_instructor', models.TextField()),
                ('teachings', models.CharField(choices=[('5', 'Very Satisfied'), ('4', 'Satisfied'), ('3', 'Neutral'), ('2', 'Dissatisfied'), ('1', 'Very Dissatisfied')], max_length=10)),
                ('expectations', models.CharField(choices=[('5', 'Strongly Agree'), ('4', 'Agree'), ('3', 'Neutral'), ('2', 'Disagree'), ('1', 'Strongly Disagree')], max_length=10)),
                ('evaluation', models.CharField(choices=[('5', 'Very Fair'), ('4', 'Fair'), ('3', 'Neutral'), ('2', 'Unfair'), ('1', 'Very Unfair')], max_length=10)),
                ('suggestion', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
