# Generated by Django 4.2.4 on 2023-08-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefeedback',
            old_name='q2_choice',
            new_name='course_remarks',
        ),
        migrations.RenameField(
            model_name='coursefeedback',
            old_name='q1_choice',
            new_name='course_satisfaction',
        ),
        migrations.RemoveField(
            model_name='coursefeedback',
            name='additional_rating',
        ),
        migrations.AddField(
            model_name='coursefeedback',
            name='select_course',
            field=models.CharField(choices=[('software_engineering', 'Bachelor of Science in Software Engineering'), ('computer_science', 'Bachelor of Science in Computer Science'), ('infosystems_technology', 'Bachelor of Science in Information Systems and Technology')], default='default_value', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursefeedback',
            name='select_year',
            field=models.CharField(choices=[('year_1', 'YEAR 1'), ('year_2', 'YEAR 2'), ('year_3', 'YEAR 3'), ('year_4', 'YEAR 4')], default='default_value', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campusfeedback',
            name='preferred_building',
            field=models.CharField(choices=[('building_a', 'COSCIS main building'), ('building_b', 'College Library'), ('building_c', 'Auditorium')], max_length=50),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='course_unit',
            field=models.CharField(choices=[('courseunit_1', 'Mobile Programming'), ('courseunit_2', 'Requirements Engineering'), ('courseunit_3', 'Artificial Intelligence'), ('courseunit_4', 'Data Communication'), ('courseunit_5', 'Object Oriented Programming'), ('courseunit_6', 'Computer Networks'), ('courseunit_7', 'Operating Systems'), ('courseunit_8', 'Database Management'), ('courseunit_9', 'Emerging Web Technologies'), ('courseunit_10', 'Data Structures and Algorithms')], max_length=50),
        ),
    ]
