# Generated by Django 4.2.4 on 2023-08-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_q2_choice_coursefeedback_course_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorfeedback',
            old_name='q2_choice',
            new_name='expectations',
        ),
        migrations.RenameField(
            model_name='instructorfeedback',
            old_name='q1_choice',
            new_name='teachings',
        ),
        migrations.RemoveField(
            model_name='instructorfeedback',
            name='additional_rating',
        ),
        migrations.RemoveField(
            model_name='instructorfeedback',
            name='student_name',
        ),
        migrations.AddField(
            model_name='instructorfeedback',
            name='evaluation',
            field=models.CharField(choices=[('5', 'Very Fair'), ('4', 'Fair'), ('3', 'Neutral'), ('2', 'Unfair'), ('1', 'Very Unfair')], default='default_value', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructorfeedback',
            name='instructor_name',
            field=models.CharField(choices=[('mumbere_alice', 'Dr Mumbere Alice'), ('agaba_martha', 'Dr Agaba Martha'), ('rogers_ntanda', 'Professor Rogers Ntanda'), ('ariho_geoffrey', 'Dr Ariho Geoffrey'), ('birimumaaso_conrad', 'Dr Birimumaaso Conrad')], max_length=50),
        ),
    ]
