# Generated by Django 4.2.4 on 2023-08-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_q2_choice_instructorfeedback_expectations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campusfeedback',
            old_name='q1_choice',
            new_name='campus_facilities',
        ),
        migrations.RenameField(
            model_name='campusfeedback',
            old_name='q2_choice',
            new_name='cleanliness_maintanance',
        ),
        migrations.RemoveField(
            model_name='campusfeedback',
            name='student_name',
        ),
        migrations.AddField(
            model_name='campusfeedback',
            name='campus_resources',
            field=models.CharField(choices=[('5', 'Very Accessible'), ('4', 'Accessible'), ('3', 'Neutral'), ('2', 'Unaccessible'), ('1', 'Very Unaccessible')], default='default_value', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campusfeedback',
            name='campus_security',
            field=models.CharField(choices=[('5', 'Very Satisfied'), ('4', 'Satisfied'), ('3', 'Neutral'), ('2', 'Dissatisfied'), ('1', 'Very Dissatisfied')], default='default_value', max_length=10),
            preserve_default=False,
        ),
    ]
