# Generated by Django 4.2.4 on 2023-08-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_q1_choice_campusfeedback_campus_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusfeedback',
            name='cleanliness_maintanance',
            field=models.CharField(choices=[('5', 'Very Clean'), ('4', 'Clean'), ('3', 'Neutral'), ('2', 'Dirty'), ('1', 'Very Dirty')], max_length=10),
        ),
    ]
