# Generated by Django 4.2.4 on 2023-08-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.CharField(default=" ", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
